-- Run this once in the Supabase SQL editor if dishes already exist without calories_estimate.
-- Safe to re-run: adds the column if missing, then backfills the 96 menu dishes by name.
-- These are rough per-portion estimates (kcal), not a nutritionist's figures.

alter table public.dishes add column if not exists calories_estimate int not null default 0;

update public.dishes set calories_estimate = 130 where name = 'Saumon' and category_id = (select id from public.categories where name = 'Sashimis');
update public.dishes set calories_estimate = 220 where name = 'Saumon' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 220 where name = 'Thon' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 290 where name = 'Neige cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 160 where name = 'Concombre' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 290 where name = 'Cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 270 where name = 'Avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 340 where name = 'Florida saumon grille cheese avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 340 where name = 'California cheese avocat sesame' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 340 where name = 'Florida saumon cheese avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 330 where name = 'California Royal saumon cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 310 where name = 'California Royal saumon avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 380 where name = 'Tempura crevette avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 400 where name = 'California fume saumon foie gras avocat cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 290 where name = 'Neige saumon cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 270 where name = 'Printemps saumon avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 390 where name = 'Oignon croustillant avocat concombre cheese' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 260 where name = 'California Royal neige' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 270 where name = 'Florida carotte saumon avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 280 where name = 'Printemps cheese avocat concombre' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 270 where name = 'California saumon avocat' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 270 where name = 'California thon cuit avocat sesame' and category_id = (select id from public.categories where name = 'Makis');
update public.dishes set calories_estimate = 180 where name = 'Saumon' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Saumon grille' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Crevette' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Maquereau' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 230 where name = 'Saumon avocat' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 300 where name = 'Tartare de saumon sur bol de riz vinaigre' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 120 where name = 'Salade de saumon' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Sashimi saumon' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Sashimi maquereau' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Ikura ouefs de saumon' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Sushi thon' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Sushi daurade' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 250 where name = 'Saumon cheese' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 270 where name = 'Florida curry saumon avocat' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 230 where name = 'Maki tobiko saumon avocat' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 340 where name = 'Maki anguille tempura crevette avocat' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 270 where name = 'California Royal saumon grille avocat' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 300 where name = 'Tranches de saumon x6 sur bol de riz vinaigre' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 360 where name = 'Anguilles fumees x6 sur bol de riz vinaigre' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 300 where name = 'Tartare saumon grille asperge crevettes sur riz vinaigre' and category_id = (select id from public.categories where name = 'Sushis');
update public.dishes set calories_estimate = 180 where name = 'Boeuf sate' and category_id = (select id from public.categories where name = 'Nos specialites');
update public.dishes set calories_estimate = 180 where name = 'Agneau sate' and category_id = (select id from public.categories where name = 'Nos specialites');
update public.dishes set calories_estimate = 70 where name = 'Soupe miso' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 120 where name = 'Salade maison' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Bouchees de porc a la vapeur' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Raviolis de crevettes a la vapeur' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 290 where name = 'Beignets de calamar' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Samoussa au boeuf' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Nams au poulet' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Rouleau de printemps (cahuete/mayo)' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 420 where name = 'Frites' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Raviolis grilles poulet' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 220 where name = 'Nouilles sautees legumes' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 300 where name = 'Riz cantonais' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 300 where name = 'Riz cantonnais fruits de mer' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 250 where name = 'Riz' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 180 where name = 'Wings' and category_id = (select id from public.categories where name = 'Entrees');
update public.dishes set calories_estimate = 560 where name = 'Poisson saute sauce aigre-douce' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Poisson saute gingimbre ciboulette' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Crevettes sauce Sichuan' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Boeuf saute poivre noir' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Porc sauce aigre douce cantonnaise' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Poulet saute champignons noirs' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Boeuf saute oignons' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 590 where name = 'Poulet croustillant du chef' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 560 where name = 'Canard laque' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 460 where name = 'Legumes sautes nature' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Poulet au basilic thailandais' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Poulet au curry' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Boeuf au basilic thailandais' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Boeuf au curry' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 600 where name = 'Bobun' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Poulet sauce aigre douce cantonaise' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Crevettes sel poivre sautes aux oignons' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 590 where name = 'Poulet pane' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 660 where name = 'Tempura fromage' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 590 where name = 'Beignets de crevettes' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 480 where name = 'Moules thailandaises' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Crevettes au curry' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 480 where name = 'Crevettes au basili thailandais' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Fruits de mer au basilic thailandais' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 520 where name = 'Fruits de mer au curry' and category_id = (select id from public.categories where name = 'Plats du chef');
update public.dishes set calories_estimate = 170 where name = 'Boeuf' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 240 where name = 'Boeuf fromage' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Poulet' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Boulettes de poulet' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Champignons' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Courgettes' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Saumon (1 paire/personne)' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 170 where name = 'Brochettes de gambas' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 350 where name = 'Grande brochette de boeuf' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 350 where name = 'Grande brochette d''agneau' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 350 where name = 'Grande brochette de saumon' and category_id = (select id from public.categories where name = 'Brochettes');
update public.dishes set calories_estimate = 350 where name = 'Grande brochette de poulet' and category_id = (select id from public.categories where name = 'Brochettes');
