-- Seed data extracted from reference/s-grill.xlsx (Round 1 sheet).
-- Run once after schema.sql, on a fresh project.

insert into public.categories (name, sort_order) values
  ('Sashimis', 0),
  ('Makis', 1),
  ('Sushis', 2),
  ('Nos specialites', 3),
  ('Entrees', 4),
  ('Plats du chef', 5),
  ('Brochettes', 6);

insert into public.dishes (category_id, name, evening_and_holidays_only) values
  ((select id from public.categories where name = 'Sashimis'), 'Saumon', false),
  ((select id from public.categories where name = 'Makis'), 'Saumon', false),
  ((select id from public.categories where name = 'Makis'), 'Thon', false),
  ((select id from public.categories where name = 'Makis'), 'Neige cheese', false),
  ((select id from public.categories where name = 'Makis'), 'Concombre', false),
  ((select id from public.categories where name = 'Makis'), 'Cheese', false),
  ((select id from public.categories where name = 'Makis'), 'Avocat', false),
  ((select id from public.categories where name = 'Makis'), 'Florida saumon grille cheese avocat', false),
  ((select id from public.categories where name = 'Makis'), 'California cheese avocat sesame', false),
  ((select id from public.categories where name = 'Makis'), 'Florida saumon cheese avocat', false),
  ((select id from public.categories where name = 'Makis'), 'California Royal saumon cheese', false),
  ((select id from public.categories where name = 'Makis'), 'California Royal saumon avocat', false),
  ((select id from public.categories where name = 'Makis'), 'Tempura crevette avocat', false),
  ((select id from public.categories where name = 'Makis'), 'California fume saumon foie gras avocat cheese', false),
  ((select id from public.categories where name = 'Makis'), 'Neige saumon cheese', false),
  ((select id from public.categories where name = 'Makis'), 'Printemps saumon avocat', false),
  ((select id from public.categories where name = 'Makis'), 'Oignon croustillant avocat concombre cheese', false),
  ((select id from public.categories where name = 'Makis'), 'California Royal neige', false),
  ((select id from public.categories where name = 'Makis'), 'Florida carotte saumon avocat', false),
  ((select id from public.categories where name = 'Makis'), 'Printemps cheese avocat concombre', false),
  ((select id from public.categories where name = 'Makis'), 'California saumon avocat', false),
  ((select id from public.categories where name = 'Makis'), 'California thon cuit avocat sesame', false),
  ((select id from public.categories where name = 'Sushis'), 'Saumon', false),
  ((select id from public.categories where name = 'Sushis'), 'Saumon grille', false),
  ((select id from public.categories where name = 'Sushis'), 'Crevette', false),
  ((select id from public.categories where name = 'Sushis'), 'Maquereau', false),
  ((select id from public.categories where name = 'Sushis'), 'Saumon avocat', false),
  ((select id from public.categories where name = 'Sushis'), 'Tartare de saumon sur bol de riz vinaigre', false),
  ((select id from public.categories where name = 'Sushis'), 'Salade de saumon', false),
  ((select id from public.categories where name = 'Sushis'), 'Sashimi saumon', true),
  ((select id from public.categories where name = 'Sushis'), 'Sashimi maquereau', true),
  ((select id from public.categories where name = 'Sushis'), 'Ikura ouefs de saumon', true),
  ((select id from public.categories where name = 'Sushis'), 'Sushi thon', true),
  ((select id from public.categories where name = 'Sushis'), 'Sushi daurade', true),
  ((select id from public.categories where name = 'Sushis'), 'Saumon cheese', true),
  ((select id from public.categories where name = 'Sushis'), 'Florida curry saumon avocat', true),
  ((select id from public.categories where name = 'Sushis'), 'Maki tobiko saumon avocat', true),
  ((select id from public.categories where name = 'Sushis'), 'Maki anguille tempura crevette avocat', true),
  ((select id from public.categories where name = 'Sushis'), 'California Royal saumon grille avocat', true),
  ((select id from public.categories where name = 'Sushis'), 'Tranches de saumon x6 sur bol de riz vinaigre', true),
  ((select id from public.categories where name = 'Sushis'), 'Anguilles fumees x6 sur bol de riz vinaigre', true),
  ((select id from public.categories where name = 'Sushis'), 'Tartare saumon grille asperge crevettes sur riz vinaigre', true),
  ((select id from public.categories where name = 'Nos specialites'), 'Boeuf sate', false),
  ((select id from public.categories where name = 'Nos specialites'), 'Agneau sate', false),
  ((select id from public.categories where name = 'Entrees'), 'Soupe miso', false),
  ((select id from public.categories where name = 'Entrees'), 'Salade maison', false),
  ((select id from public.categories where name = 'Entrees'), 'Bouchees de porc a la vapeur', false),
  ((select id from public.categories where name = 'Entrees'), 'Raviolis de crevettes a la vapeur', false),
  ((select id from public.categories where name = 'Entrees'), 'Beignets de calamar', false),
  ((select id from public.categories where name = 'Entrees'), 'Samoussa au boeuf', false),
  ((select id from public.categories where name = 'Entrees'), 'Nams au poulet', false),
  ((select id from public.categories where name = 'Entrees'), 'Rouleau de printemps (cahuete/mayo)', false),
  ((select id from public.categories where name = 'Entrees'), 'Frites', false),
  ((select id from public.categories where name = 'Entrees'), 'Raviolis grilles poulet', false),
  ((select id from public.categories where name = 'Entrees'), 'Nouilles sautees legumes', false),
  ((select id from public.categories where name = 'Entrees'), 'Riz cantonais', false),
  ((select id from public.categories where name = 'Entrees'), 'Riz cantonnais fruits de mer', false),
  ((select id from public.categories where name = 'Entrees'), 'Riz', false),
  ((select id from public.categories where name = 'Entrees'), 'Wings', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poisson saute sauce aigre-douce', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poisson saute gingimbre ciboulette', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes sauce Sichuan', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf saute poivre noir', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Porc sauce aigre douce cantonnaise', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet saute champignons noirs', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf saute oignons', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet croustillant du chef', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Canard laque', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Legumes sautes nature', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet au basilic thailandais', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet au curry', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf au basilic thailandais', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf au curry', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Bobun', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet sauce aigre douce cantonaise', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes sel poivre sautes aux oignons', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet pane', false),
  ((select id from public.categories where name = 'Plats du chef'), 'Tempura fromage', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Beignets de crevettes', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Moules thailandaises', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes au curry', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes au basili thailandais', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Fruits de mer au basilic thailandais', true),
  ((select id from public.categories where name = 'Plats du chef'), 'Fruits de mer au curry', true),
  ((select id from public.categories where name = 'Brochettes'), 'Boeuf', false),
  ((select id from public.categories where name = 'Brochettes'), 'Boeuf fromage', false),
  ((select id from public.categories where name = 'Brochettes'), 'Poulet', false),
  ((select id from public.categories where name = 'Brochettes'), 'Boulettes de poulet', false),
  ((select id from public.categories where name = 'Brochettes'), 'Champignons', false),
  ((select id from public.categories where name = 'Brochettes'), 'Courgettes', false),
  ((select id from public.categories where name = 'Brochettes'), 'Saumon (1 paire/personne)', false),
  ((select id from public.categories where name = 'Brochettes'), 'Brochettes de gambas', true),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de boeuf', true),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette d''agneau', true),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de saumon', true),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de poulet', true);
