-- Seed data extracted from reference/s-grill.xlsx (Round 1 sheet).
-- Run once after schema.sql, on a fresh project.
-- calories_estimate is a rough per-portion estimate, not a nutritionist's figure.

insert into public.categories (name, sort_order) values
  ('Sashimis', 0),
  ('Makis', 1),
  ('Sushis', 2),
  ('Nos specialites', 3),
  ('Entrees', 4),
  ('Plats du chef', 5),
  ('Brochettes', 6);

insert into public.dishes (category_id, name, evening_and_holidays_only, calories_estimate) values
  ((select id from public.categories where name = 'Sashimis'), 'Saumon', false, 130),
  ((select id from public.categories where name = 'Makis'), 'Saumon', false, 220),
  ((select id from public.categories where name = 'Makis'), 'Thon', false, 220),
  ((select id from public.categories where name = 'Makis'), 'Neige cheese', false, 290),
  ((select id from public.categories where name = 'Makis'), 'Concombre', false, 160),
  ((select id from public.categories where name = 'Makis'), 'Cheese', false, 290),
  ((select id from public.categories where name = 'Makis'), 'Avocat', false, 270),
  ((select id from public.categories where name = 'Makis'), 'Florida saumon grille cheese avocat', false, 340),
  ((select id from public.categories where name = 'Makis'), 'California cheese avocat sesame', false, 340),
  ((select id from public.categories where name = 'Makis'), 'Florida saumon cheese avocat', false, 340),
  ((select id from public.categories where name = 'Makis'), 'California Royal saumon cheese', false, 330),
  ((select id from public.categories where name = 'Makis'), 'California Royal saumon avocat', false, 310),
  ((select id from public.categories where name = 'Makis'), 'Tempura crevette avocat', false, 380),
  ((select id from public.categories where name = 'Makis'), 'California fume saumon foie gras avocat cheese', false, 400),
  ((select id from public.categories where name = 'Makis'), 'Neige saumon cheese', false, 290),
  ((select id from public.categories where name = 'Makis'), 'Printemps saumon avocat', false, 270),
  ((select id from public.categories where name = 'Makis'), 'Oignon croustillant avocat concombre cheese', false, 390),
  ((select id from public.categories where name = 'Makis'), 'California Royal neige', false, 260),
  ((select id from public.categories where name = 'Makis'), 'Florida carotte saumon avocat', false, 270),
  ((select id from public.categories where name = 'Makis'), 'Printemps cheese avocat concombre', false, 280),
  ((select id from public.categories where name = 'Makis'), 'California saumon avocat', false, 270),
  ((select id from public.categories where name = 'Makis'), 'California thon cuit avocat sesame', false, 270),
  ((select id from public.categories where name = 'Sushis'), 'Saumon', false, 180),
  ((select id from public.categories where name = 'Sushis'), 'Saumon grille', false, 180),
  ((select id from public.categories where name = 'Sushis'), 'Crevette', false, 180),
  ((select id from public.categories where name = 'Sushis'), 'Maquereau', false, 180),
  ((select id from public.categories where name = 'Sushis'), 'Saumon avocat', false, 230),
  ((select id from public.categories where name = 'Sushis'), 'Tartare de saumon sur bol de riz vinaigre', false, 300),
  ((select id from public.categories where name = 'Sushis'), 'Salade de saumon', false, 120),
  ((select id from public.categories where name = 'Sushis'), 'Sashimi saumon', true, 180),
  ((select id from public.categories where name = 'Sushis'), 'Sashimi maquereau', true, 180),
  ((select id from public.categories where name = 'Sushis'), 'Ikura ouefs de saumon', true, 180),
  ((select id from public.categories where name = 'Sushis'), 'Sushi thon', true, 180),
  ((select id from public.categories where name = 'Sushis'), 'Sushi daurade', true, 180),
  ((select id from public.categories where name = 'Sushis'), 'Saumon cheese', true, 250),
  ((select id from public.categories where name = 'Sushis'), 'Florida curry saumon avocat', true, 270),
  ((select id from public.categories where name = 'Sushis'), 'Maki tobiko saumon avocat', true, 230),
  ((select id from public.categories where name = 'Sushis'), 'Maki anguille tempura crevette avocat', true, 340),
  ((select id from public.categories where name = 'Sushis'), 'California Royal saumon grille avocat', true, 270),
  ((select id from public.categories where name = 'Sushis'), 'Tranches de saumon x6 sur bol de riz vinaigre', true, 300),
  ((select id from public.categories where name = 'Sushis'), 'Anguilles fumees x6 sur bol de riz vinaigre', true, 360),
  ((select id from public.categories where name = 'Sushis'), 'Tartare saumon grille asperge crevettes sur riz vinaigre', true, 300),
  ((select id from public.categories where name = 'Nos specialites'), 'Boeuf sate', false, 180),
  ((select id from public.categories where name = 'Nos specialites'), 'Agneau sate', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Soupe miso', false, 70),
  ((select id from public.categories where name = 'Entrees'), 'Salade maison', false, 120),
  ((select id from public.categories where name = 'Entrees'), 'Bouchees de porc a la vapeur', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Raviolis de crevettes a la vapeur', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Beignets de calamar', false, 290),
  ((select id from public.categories where name = 'Entrees'), 'Samoussa au boeuf', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Nams au poulet', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Rouleau de printemps (cahuete/mayo)', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Frites', false, 420),
  ((select id from public.categories where name = 'Entrees'), 'Raviolis grilles poulet', false, 180),
  ((select id from public.categories where name = 'Entrees'), 'Nouilles sautees legumes', false, 220),
  ((select id from public.categories where name = 'Entrees'), 'Riz cantonais', false, 300),
  ((select id from public.categories where name = 'Entrees'), 'Riz cantonnais fruits de mer', false, 300),
  ((select id from public.categories where name = 'Entrees'), 'Riz', false, 250),
  ((select id from public.categories where name = 'Entrees'), 'Wings', false, 180),
  ((select id from public.categories where name = 'Plats du chef'), 'Poisson saute sauce aigre-douce', false, 560),
  ((select id from public.categories where name = 'Plats du chef'), 'Poisson saute gingimbre ciboulette', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes sauce Sichuan', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf saute poivre noir', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Porc sauce aigre douce cantonnaise', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet saute champignons noirs', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf saute oignons', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet croustillant du chef', false, 590),
  ((select id from public.categories where name = 'Plats du chef'), 'Canard laque', false, 560),
  ((select id from public.categories where name = 'Plats du chef'), 'Legumes sautes nature', false, 460),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet au basilic thailandais', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet au curry', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf au basilic thailandais', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Boeuf au curry', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Bobun', false, 600),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet sauce aigre douce cantonaise', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes sel poivre sautes aux oignons', false, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Poulet pane', false, 590),
  ((select id from public.categories where name = 'Plats du chef'), 'Tempura fromage', true, 660),
  ((select id from public.categories where name = 'Plats du chef'), 'Beignets de crevettes', true, 590),
  ((select id from public.categories where name = 'Plats du chef'), 'Moules thailandaises', true, 480),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes au curry', true, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Crevettes au basili thailandais', true, 480),
  ((select id from public.categories where name = 'Plats du chef'), 'Fruits de mer au basilic thailandais', true, 520),
  ((select id from public.categories where name = 'Plats du chef'), 'Fruits de mer au curry', true, 520),
  ((select id from public.categories where name = 'Brochettes'), 'Boeuf', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Boeuf fromage', false, 240),
  ((select id from public.categories where name = 'Brochettes'), 'Poulet', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Boulettes de poulet', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Champignons', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Courgettes', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Saumon (1 paire/personne)', false, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Brochettes de gambas', true, 170),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de boeuf', true, 350),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette d''agneau', true, 350),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de saumon', true, 350),
  ((select id from public.categories where name = 'Brochettes'), 'Grande brochette de poulet', true, 350);
